# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: opentelemetry/proto/resource/v1/resource.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from typing import List

import betterproto

from ...common import v1 as __common_v1__


@dataclass(eq=False, repr=False)
class Resource(betterproto.Message):
    """Resource information."""

    attributes: List["__common_v1__.KeyValue"] = betterproto.message_field(1)
    """
    Set of attributes that describe the resource.
     Attribute keys MUST be unique (it is not allowed to have more than one
     attribute with the same key).
    """

    dropped_attributes_count: int = betterproto.uint32_field(2)
    """
    dropped_attributes_count is the number of dropped attributes. If the value is 0, then
     no attributes were dropped.
    """
