receivers:
  otlp:
    protocols:
      http:
      grpc:

exporters:
  file:
    path: "last_telemetry_dump.json"

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [file]
  #   metrics:
  #     receivers: [otlp]
  #     exporters: [debug]
  #     processors: [batch]
  #   logs:
  #     receivers: [otlp]
  #     exporters: [debug]
  #     processors: [batch]
