receivers:
  otlpjsonfile:
    include:
      - "telemetry_dump/*.json"

exporters:
  debug:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlpjsonfile]
      exporters: [debug]
  #   metrics:
  #     receivers: [otlp]
  #     exporters: [debug]
  #     processors: [batch]
  #   logs:
  #     receivers: [otlp]
  #     exporters: [debug]
  #     processors: [batch]
