receivers:
  otlp:
    protocols:
      http:
      grpc:

exporters:
  file:
    path: "last_telemetry_dump.json"
  otlp:
    endpoint: 127.0.0.1:11417
    tls:
      insecure: true
    compression: none

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp,file]
  #   metrics:
  #     receivers: [otlp]
  #     exporters: [debug]
  #     processors: [batch]
  #   logs:
  #     receivers: [otlp]
  #     exporters: [debug]
  #     processors: [batch]
